### ISSUE TITLE
very small bug in proboot 3

### ISSUE THREAD

**Issue by dimitrivisser** [ComBoot/ComBoot#17]
Hi,

I found a very small missalignment in /forum/viewforum.php?f=1

It is the page where you can view the content of the (first) category. The "mark subforums as read" is alligned too much to the right.

I can give you the code to correct this, but I think you can do better yourself ;-)

![proboot3](https://f.cloud.github.com/assets/7057744/2510974/84c69f30-b40f-11e3-8875-b03245e47436.png)

Very nice work!

**Comment by TheZoker** [comment]
Thats strange, because on my demo page, everything is working fine:
![img_2014 03 25_15h18m27s_001_](https://f.cloud.github.com/assets/1368405/2512625/7381b584-b428-11e3-8025-1d00f1ee2e7b.png)

Also the user button on the navbar on the right, does not seem to work the way it should.

Can you send me a link to your website?

By the way:
What do you think of a member site, looking like this:
![img_2014 03 25_16h14m25s_002_](https://f.cloud.github.com/assets/1368405/2513470/30385d52-b430-11e3-9869-292bcf8a6810.png)

**Comment by dimitrivisser** [comment]
Hi Florian,

I already integrated your theme with the website. To show you I just installed your theme again, without modifications. It's a fresh download on a new phpbb install.

The link is http://www.weddingpages.nl/forum/viewforum.php?f=1
To see it you need to login, username is administrator password is TakkeZooi159973

I viewed the page in Chrome, Safari and Firefox on a Mac, and with IE on an old Windows notebook. The "mark subforums read" are alligned a little bit too much to the right on all browsers.

The new page looks great!  I am really very happy with your theme. I already spent a day trying to convert the old proboot theme to Bootstrap 3, till I saw your theme by accident. I have no experience with phpbb, so I think you saved me at least a week of work ;-)  Thank you very much!

I also found something else which doesn't work on http://www.weddingpages.nl/forum/viewtopic.php?f=2&t=1   Each contribution has a little arrow to go to the top of the page, but when clicking it, nothing happens.

**Comment by TheZoker** [comment]
Please update the theme and tell me, if everything works fine (for example the smooth scrolling).

If you find another bug or want another feature, dont hesitate to open an issue :)

Note: If the theme is out of beta, I will add it to phpBB.com and other theme database, so everybody can find it :) Btw: It took me much longer to transfer this theme to bootstrap 3 and add great features ;)
